# Copyright (c) 2017 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.

# Author: Diego Garcia Huerta
# Contact: https://www.linkedin.com/in/diegogh/
#
# YOU SHOULD MERGE these entries into your settings file, as
# THIS FILE BY ITSELF WILL NOT WORK 
# These are the additions to get substancepainter engine up and running with the 
# default tk-apps for this environment

# substancepainter
settings.tk-multi-shotgunpanel.substancepainter:
  action_mappings:
    PublishedFile:
    - actions: [publish_clipboard]
      filters: {}
    Task:
    - actions: [assign_task, task_to_ip]
      filters: {}
    Version:
    - actions: [quicktime_clipboard, sequence_clipboard, add_to_playlist]
      filters: {}
  location: "@apps.tk-multi-shotgunpanel.location"
